[versions]
agp = "8.13.2"
kotlin = "2.3.0"
activityKtx = "1.12.2"
webkit = "1.15.0"

[libraries]
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

